name: Deploy EC2 Instance

on:
  push:
    branches:
      - main

# Definir variables de entorno a nivel de workflow
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
    
jobs:
  deploy-ec2:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Save SSH private key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Add SSH key to the agent
      run: |
        eval "$(ssh-agent -s)"
        ssh-add TestDevOps.pem
        echo "SSH private key added to the agent."

    - name: Create EC2 Instance
      id: ec2
      run: |
        INSTANCE_ID=$(aws ec2 run-instances \
            --image-id ami-0fb6ffc8e310f461b \
            --count 1 \
            --instance-type t2.micro \
            --key-name TestDevOps \
            --security-group-ids sg-0e8bb9959030cb190 \
            --subnet-id subnet-00d0912f52be90b9c \
            --tag-specifications "ResourceType=instance,Tags=[{Key=Name,Value=GeoInstanciaGratuita}]" \
            --associate-public-ip-address \
            --output text)
          
          echo "EC2 Instance created with ID: $INSTANCE_ID"
          echo "::set-output name=instance_id::$INSTANCE_ID"

    - name: Ssh connection
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ secrets.USER_SERVER }}@${{ env.ip }} 

    - name: Clean up
      run: |
          rm TestDevOps.pem
          echo "Cleaned up SSH private key."