name: Deploy EC2 Instance

on:
  push:
    branches:
      - main

# Definir variables de entorno a nivel de workflow
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
    
jobs:
  deploy-ec2:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Save SSH private key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > TestDevOps.pem
        chmod 600 TestDevOps.pem
        echo "SSH private key saved."

    - name: Create EC2 Instance
      id: ec2
      run: |
        INSTANCE_ID=$(aws ec2 run-instances \
            --image-id ami-0fb6ffc8e310f461b \
            --count 1 \
            --instance-type t2.micro \
            --key-name TestDevOps \
            --security-group-ids sg-0e8bb9959030cb190 \
            --subnet-id subnet-00d0912f52be90b9c \
            --tag-specifications "ResourceType=instance,Tags=[{Key=Name,Value=GeoInstanciaGratuita}]" \
            --associate-public-ip-address \
            --output text)
          
          echo "EC2 Instance created with ID: $INSTANCE_ID"
          echo "::set-output name=instance_id::$INSTANCE_ID"

    - name: Wait for EC2 Instance to be running
      run: |
          echo "Waiting for the EC2 instance to be in running state..."
          while true; do
            STATE=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query 'Reservations[0].Instances[0].State.Name' --output text)
              echo "Current state: $STATE"
              if [ "$STATE" == "running" ]; then
                break
              fi
              echo "Waiting..."
              sleep 10
            done

    - name: Get Public IP Address
      id: ip
      run: |
          PUBLIC_IP=$(aws ec2 describe-instances \
            --instance-ids $INSTANCE_ID \
            --query 'Reservations[0].Instances[0].PublicIpAddress' \
            --output text)
          echo "Public IP Address: $PUBLIC_IP"
          echo "public_ip=$PUBLIC_IP" >> $GITHUB_ENV

    - name: Connect to EC2 Instance
      run: |
          echo "Connecting to EC2 Instance at IP: ${{ env.public_ip }}"
          ssh -o StrictHostKeyChecking=no -i TestDevOps.pem ec2-user@${{ env.public_ip }} "echo 'Connected to EC2 Instance'"
          echo "Connected to EC2 Instance."

    - name: Clean up
      run: |
          rm TestDevOps.pem
          echo "Cleaned up SSH private key."