name: Deploy EC2 Instance

on:
  push:
    branches:
      - main

# Definir variables de entorno a nivel de workflow
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  
jobs:
  deploy-ec2:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create EC2 Instance
      run: |
        aws ec2 run-instances \
          --image-id ami-0fb6ffc8e310f461b \
          --count 1 \
          --instance-type t2.micro \
          --key-name TestDevOps \
          --security-group-ids sg-0e8bb9959030cb190 \
          --subnet-id subnet-00d0912f52be90b9c \
          --tag-specifications "ResourceType=instance,Tags=[{Key=Name,Value=GeoInstanciaGratuita}]"